---
permalink: task-restore-virtual-machines-from-amazon-fsx.html 
sidebar: sidebar 
keywords: restore, virtual machines, amazon fsx 
summary: 還原虛擬機器時、您可以使用所選的備份複本覆寫現有內容、也可以製作虛擬機器的複本。 
---
= 從 Amazon FSX 還原虛擬機器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
還原虛擬機器時、您可以使用所選的備份複本覆寫現有內容、也可以製作虛擬機器的複本。

.開始之前
* 備份必須存在。
+
您必須先使用 BlueXP 備份和還原來建立虛擬機器的備份、然後才能還原虛擬機器。

+
[NOTE]
====
如果虛擬機器的 Snapshot 複本是由 BlueXP 備份和還原以外的軟體為虛擬機器執行、則還原作業無法成功完成。

====
* 虛擬機器不得在傳輸中。
+
您要還原的虛擬機器不得處於 VMotion 或 Storage VMotion 的狀態。

* HA 組態錯誤。
+
在將備份還原至不同位置之前、請先確認vCenter ESXi主機摘要畫面上沒有顯示HA組態錯誤。



.關於這項工作
* 虛擬機器已取消登錄、並重新登錄。
+
虛擬機器的還原作業會取消原始虛擬機器的登錄、從備份 Snapshot 複本還原虛擬機器、並在同一 ESXi 伺服器上以相同名稱和組態登錄還原的虛擬機器。還原後、您必須手動將虛擬機器新增至資源群組。

* 還原資料存放區
+
您無法還原資料存放區、但可以還原資料存放區中的任何虛擬機器。

* 虛擬機器的 VMware 一致性快照失敗。
+
即使虛擬機器的 VMware 一致性快照失敗、仍會備份虛擬機器。您可以在還原精靈中檢視備份複本中包含的實體、並將其用於還原作業。



.步驟
. 在 VMware vSphere Web Client GUI 中、按一下工具列中的 * 功能表 * 、按一下 * 清查 * 、然後選取 * 虛擬機器和範本 * 。
. 在左導覽器窗格中、以滑鼠右鍵按一下 * 虛擬機器 * 、然後在下拉式清單中選取 * NetApp 雲端備份 * 、然後選取 * 還原 * 以啟動精靈。
. 在*還原*精靈的*選取備份*頁面上、選取您要還原的備份Snapshot複本。
+
您可以搜尋特定的備份名稱或部分備份名稱、也可以按一下篩選器圖示並選取日期和時間範圍來篩選備份清單、選取是否要包含VMware Snapshot的備份、是否要掛載備份以及位置。按一下「*確定*」以返回精靈。

. 在 * 選取範圍 * 頁面上、在 * 還原範圍 * 欄位中選取 * 整個虛擬機器 * 、然後選取還原位置、然後輸入要掛載備份的目的地 ESXi 資訊。
+
還原部分備份時、還原作業會跳過「*選取範圍*」頁面。

. 如果您希望在還原作業之後開啟虛擬機器電源、請啟用 * 重新啟動 VM* 核取方塊。
. 在「*選取位置*」頁面上、選取還原資料存放區的位置。
. 檢閱 * 摘要 * 頁面、然後按一下 * 完成 * 。
. * 選用 * ：按一下畫面底部的 * 最近工作 * 來監控作業進度。


.完成後
* 將還原的虛擬機器新增至資源群組。
+
雖然虛擬機器已還原、但不會自動新增至先前的資源群組。因此、您必須手動將還原的虛擬機器新增至適當的資源群組。


