---
permalink: task-deploy-bluexp-backup-and-recovery-for-vms.html 
sidebar: sidebar 
keywords: deploy, bluexp, backup, recovery for VMs 
summary: 若要保護虛擬機器上的 VM 、資料存放區和應用程式一致的資料庫、您必須為 VM 部署 BlueXP 備份和還原。 
---
= 為 VM 部署 BlueXP 備份與還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要保護虛擬機器上的 VM 、資料存放區和應用程式一致的資料庫、您必須為 VM 部署 BlueXP 備份和還原。

.開始之前
++++

[NOTE]
====
VMware vCenter 8.0 以上版本支援 OVA 部署。

====
* 您必須閱讀部署需求。
* 您必須在 AWS 上執行支援版本的 VMC 。
* 您必須在 AWS 環境上設定和設定 VMC 。
* 您必須為虛擬機器設定 ESXi 主機以進行 BlueXP 備份與還原。
* 您必須為 VM 下載 BlueXP 備份與還原 `.tar` 檔案：
* 您必須擁有 AWS 執行個體上 VMC 的登入驗證詳細資料。
* 您必須擁有具有有效公開金鑰和私密金鑰檔案的憑證。如需詳細資訊、請參閱儲存憑證管理一節中的文章。
* 您必須登出並關閉 vSphere 用戶端的所有瀏覽器工作階段、並刪除瀏覽器快取、以避免在部署虛擬機器的 BlueXP 備份與還原期間發生瀏覽器快取問題。
* 您必須在vCenter中啟用傳輸層安全性（TLS）。請參閱VMware文件。


在與 vCenter 相同的時區中部署虛擬機器的 BlueXP 備份與還原。

.步驟
. 對於 VMware vCenter 7.0.3 及更新版本、請依照「下載開放式虛擬應用裝置（ OVA ）」一節中的步驟、將憑證匯入 vCenter 。
. 在瀏覽器中、瀏覽至VMware vSphere vCenter。
. 登入* VMware vCenter單一登入頁面*。
. 在導覽器窗格中、以滑鼠右鍵按一下任何虛擬機器的有效父物件（例如資料中心、叢集或主機）、然後選取*部署OVF範本*以啟動VMware部署精靈。
. 擷取 `.tar` 檔案、其中包含 `.ova` 將檔案儲存到您的本機系統。在「*選取OVF範本*」頁面上、指定的位置 `.ova` 檔案 `.tar` 擷取的資料夾。
. 單擊 * 下一步 * 。
. 在「*選取名稱與資料夾*」頁面上、輸入VM或vApp的唯一名稱、然後選取部署位置、再按「*下一步*」。
+
此步驟會指定匯入的位置 `.ova` 歸檔至vCenter。VM的預設名稱與所選的名稱相同 `.ova` 檔案：如果您變更預設名稱、請在 AWS VM 資料夾的每個 VMC 中選擇唯一的名稱。

+
VM的預設部署位置是啟動精靈的詳細目錄物件。

. 在「*選取資源*」頁面上、選取您要執行已部署VM範本的資源、然後按一下「*下一步*」。
. 在*檢閱詳細資料*頁面上、確認 `.ova` 範本詳細資料、然後按一下*下一步*。
. 在「*授權合約*」頁面上、勾選「*我接受所有授權合約*」核取方塊。
. 在「*選取儲存設備*」頁面上、定義儲存已部署OVF範本檔案的位置和方式。
+
.. 選取VMDK的磁碟格式。
.. 選取VM儲存原則。
+
只有在目的地資源上啟用儲存原則時、才能使用此選項。

.. 選取要儲存已部署OVA範本的資料存放區。
+
組態檔和虛擬磁碟檔案會儲存在資料存放區中。

+
選取足以容納虛擬機器或vApp及所有相關虛擬磁碟檔案的資料存放區。



. 在「*選取網路*」頁面上、執行下列動作：
+
.. 選取來源網路並將其對應至目的地網路。
+
來源網路欄會列出OVA範本中定義的所有網路。

.. 在「* IP Allocate Settings...（* IP分配設定*）」區段中、選取所需的IP傳輸協定、然後按「*下一步*」。
+
適用於 VM 的 BlueXP 備份與還原支援單一網路介面。如果您需要多個網路介面卡、則必須手動設定。



. 在*自訂範本*頁面上、執行下列動作：
+
.. 在「*登錄至現有vCenter *」區段中、輸入虛擬應用裝置的vCenter名稱和vCenter認證。
+
在 *vCenter UserName* 欄位中、以網域 \ 使用者名稱格式輸入使用者名稱。

.. 在 * 建立 BlueXP 備份與還原 VM 認證 * 區段中、輸入本機認證。
+
在*使用者名稱*欄位中、輸入本機使用者名稱；請勿包含網域詳細資料。

+
[IMPORTANT]
====
記下您指定的使用者名稱和密碼。如果您想稍後修改 VM 組態的 BlueXP 備份與還原、則需要使用這些認證。

====
.. 輸入主要使用者的認證資料。
.. 在*設定網路內容*中、輸入主機名稱。
+
... 在「*設定IPV4網路內容*」區段中、輸入網路資訊、例如：IPV4位址、IPV4網路遮罩、IPV4閘道、IPV4主要DNS、IPV4次要DNS、 和IPv4搜尋網域。
+
[IMPORTANT]
====
如果您要繼續使用 DHCP 做為網路組態、您可以跳過這些步驟、並將「設定網路內容」區段中的項目保留空白。

====


.. 在*設定日期與時間*中、選取vCenter所在的時區。


. 在「*準備完成*」頁面上、檢閱頁面、然後按一下「*完成*」。
+
所有主機都必須設定IP位址（不支援FQDN主機名稱）。部署作業不會在部署之前驗證您的輸入。

+
您可以從「近期工作」視窗檢視部署進度、同時等待OVF匯入和部署工作完成。

+
當成功部署虛擬機器的 BlueXP 備份與還原時、會將其部署為 Linux VM 、並向 vCenter 註冊、然後安裝 VMware vSphere 用戶端。

. 瀏覽至已部署虛擬機器 BlueXP 備份與還原的虛擬機器、然後按一下 * Summary （摘要） * 索引標籤、再按一下 * Power On* （ * 開機）方塊以啟動虛擬應用裝置。
. 當虛擬機器的 BlueXP 備份與還原功能啟動時、請以滑鼠右鍵按一下虛擬機器的已部署 BlueXP 備份與還原、選取 * 來賓作業系統 * 、然後按一下 * 安裝 VMware 工具 * 。

